-- Phase 5: people, membership and contribution.
-- Generated by drizzle-kit from src/db/schema.ts, then narrowed to the new
-- Phase 5 objects: migrations 0004/0005 predate the snapshot chain and were
-- hand-written, so a raw regenerate would re-emit Phase 4 tables.
CREATE TABLE "member_achievements" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"category" text NOT NULL,
	"achieved_at" timestamp with time zone NOT NULL,
	"issuer_id" text NOT NULL,
	"visibility" text DEFAULT 'members' NOT NULL,
	"verification_status" text DEFAULT 'unreviewed' NOT NULL,
	"evidence_id" text,
	"source_entity_type" text,
	"source_entity_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "achievement_verification" CHECK ("member_achievements"."verification_status" in ('unreviewed','verified','rejected')),
	CONSTRAINT "achievement_visibility" CHECK ("member_achievements"."visibility" in ('management','committee','members'))
);
--> statement-breakpoint
CREATE TABLE "application_reviews" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"application_id" text NOT NULL,
	"reviewer_id" text NOT NULL,
	"previous_status" text NOT NULL,
	"new_status" text NOT NULL,
	"decision" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "badge_definitions" (
	"key" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"icon" text DEFAULT 'award' NOT NULL,
	"rule" jsonb NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"repeatable" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contribution_rules" (
	"key" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"metric" text NOT NULL,
	"threshold" integer DEFAULT 1 NOT NULL,
	"xp_points" integer DEFAULT 0 NOT NULL,
	"impact_points" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member_handovers" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"kind" text NOT NULL,
	"committee_id" text,
	"successor_id" text,
	"responsibilities" text DEFAULT '' NOT NULL,
	"active_tasks" text DEFAULT '' NOT NULL,
	"pending_decisions" text DEFAULT '' NOT NULL,
	"active_events" text DEFAULT '' NOT NULL,
	"files" text DEFAULT '' NOT NULL,
	"resources" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"completed_at" timestamp with time zone,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "handover_status" CHECK ("member_handovers"."status" in ('pending','completed'))
);
--> statement-breakpoint
CREATE TABLE "impact_transactions" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" text NOT NULL,
	"points" integer NOT NULL,
	"source_type" text NOT NULL,
	"source_id" text,
	"reason" text NOT NULL,
	"rule_key" text,
	"automatic" boolean DEFAULT true NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "impact_points_sign" CHECK ("impact_transactions"."points" <> 0)
);
--> statement-breakpoint
CREATE TABLE "member_badges" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" text NOT NULL,
	"badge_key" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"awarded_by" text NOT NULL,
	"awarded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"revoke_reason" text DEFAULT '' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "member_committee_history" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"committee_id" text NOT NULL,
	"academic_term_id" text NOT NULL,
	"assignment_type" text DEFAULT 'permanent' NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"placed_by" text NOT NULL,
	"start_at" timestamp with time zone DEFAULT now() NOT NULL,
	"end_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "member_profiles" (
	"user_id" text PRIMARY KEY NOT NULL,
	"student_id" text,
	"phone" text,
	"major" text,
	"college" text,
	"academic_level" text,
	"gender" text,
	"joined_at" timestamp with time zone,
	"status" text DEFAULT 'new' NOT NULL,
	"status_reason" text,
	"skills" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"interests" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"development_goals" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"previous_experience" text DEFAULT '' NOT NULL,
	"preferred_areas" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"availability" text DEFAULT '' NOT NULL,
	"motivation" text DEFAULT '' NOT NULL,
	"management_notes" text DEFAULT '' NOT NULL,
	"image_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "member_status" CHECK ("member_profiles"."status" in ('new','active','low_engagement','inactive','withdrawn','archived'))
);
--> statement-breakpoint
CREATE TABLE "member_role_history" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"club_role" text NOT NULL,
	"previous_club_role" text,
	"committee_id" text,
	"academic_term_id" text,
	"reason" text DEFAULT '' NOT NULL,
	"assigned_by" text NOT NULL,
	"start_at" timestamp with time zone DEFAULT now() NOT NULL,
	"end_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "member_status_history" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"previous_status" text,
	"new_status" text NOT NULL,
	"reason" text DEFAULT '' NOT NULL,
	"changed_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "membership_applications" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"full_name" text NOT NULL,
	"student_id" text NOT NULL,
	"major" text DEFAULT '' NOT NULL,
	"email" text NOT NULL,
	"phone" text DEFAULT '' NOT NULL,
	"skills" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"interests" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"previous_experience" text DEFAULT '' NOT NULL,
	"preferred_committee_id" text,
	"alternate_committee_id" text,
	"motivation" text DEFAULT '' NOT NULL,
	"development_goals" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"availability" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"academic_term_id" text NOT NULL,
	"assigned_reviewer_id" text,
	"converted_user_id" text,
	"decided_at" timestamp with time zone,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "application_status" CHECK ("membership_applications"."status" in ('submitted','under_review','shortlisted','interview','accepted','rejected','waitlisted','converted'))
);
--> statement-breakpoint
CREATE TABLE "mentor_assignments" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"mentor_id" text NOT NULL,
	"mentee_id" text NOT NULL,
	"academic_term_id" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"follow_up_at" timestamp with time zone,
	"assigned_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	CONSTRAINT "no_self_mentoring" CHECK ("mentor_assignments"."mentor_id" <> "mentor_assignments"."mentee_id"),
	CONSTRAINT "mentor_status" CHECK ("mentor_assignments"."status" in ('active','completed','ended'))
);
--> statement-breakpoint
CREATE TABLE "onboarding_plans" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"academic_term_id" text NOT NULL,
	"status" text DEFAULT 'in_progress' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"created_by" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "onboarding_steps" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"plan_id" text NOT NULL,
	"step_key" text NOT NULL,
	"title" text NOT NULL,
	"position" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"owner_id" text,
	"due_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"completion_note" text DEFAULT '' NOT NULL,
	"linked_work_id" text,
	"linked_event_id" text,
	"completed_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "onboarding_step_status" CHECK ("onboarding_steps"."status" in ('pending','in_progress','completed','skipped'))
);
--> statement-breakpoint
CREATE TABLE "people_events" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_id" text,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"member_id" text,
	"committee_id" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transfer_requests" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"from_committee_id" text,
	"to_committee_id" text NOT NULL,
	"reason" text NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'requested' NOT NULL,
	"requested_by" text NOT NULL,
	"reviewed_by" text,
	"decision_notes" text DEFAULT '' NOT NULL,
	"decided_at" timestamp with time zone,
	"effective_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "transfer_status" CHECK ("transfer_requests"."status" in ('requested','approved','rejected'))
);
--> statement-breakpoint
CREATE TABLE "volunteer_hour_entries" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" text NOT NULL,
	"source_type" text NOT NULL,
	"source_id" text,
	"activity_title" text NOT NULL,
	"date" timestamp with time zone NOT NULL,
	"hours" integer NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"submitted_by" text NOT NULL,
	"approver_id" text,
	"decision_notes" text DEFAULT '' NOT NULL,
	"decided_at" timestamp with time zone,
	"evidence_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "volunteer_status" CHECK ("volunteer_hour_entries"."status" in ('pending','approved','rejected')),
	CONSTRAINT "volunteer_hours_positive" CHECK ("volunteer_hour_entries"."hours" > 0),
	CONSTRAINT "volunteer_hours_integer" CHECK ("volunteer_hour_entries"."hours" = round("volunteer_hour_entries"."hours"))
);
--> statement-breakpoint
CREATE TABLE "xp_transactions" (
	"id" text PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_id" text NOT NULL,
	"points" integer NOT NULL,
	"source_type" text NOT NULL,
	"source_id" text,
	"reason" text NOT NULL,
	"rule_key" text,
	"automatic" boolean DEFAULT true NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "xp_points_sign" CHECK ("xp_transactions"."points" <> 0)
);
--> statement-breakpoint
ALTER TABLE "member_achievements" ADD CONSTRAINT "member_achievements_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_achievements" ADD CONSTRAINT "member_achievements_issuer_id_users_id_fk" FOREIGN KEY ("issuer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_achievements" ADD CONSTRAINT "member_achievements_evidence_id_evidence_id_fk" FOREIGN KEY ("evidence_id") REFERENCES "public"."evidence"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "application_reviews" ADD CONSTRAINT "application_reviews_application_id_membership_applications_id_fk" FOREIGN KEY ("application_id") REFERENCES "public"."membership_applications"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "application_reviews" ADD CONSTRAINT "application_reviews_reviewer_id_users_id_fk" FOREIGN KEY ("reviewer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_handovers" ADD CONSTRAINT "member_handovers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_handovers" ADD CONSTRAINT "member_handovers_committee_id_committees_id_fk" FOREIGN KEY ("committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_handovers" ADD CONSTRAINT "member_handovers_successor_id_users_id_fk" FOREIGN KEY ("successor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_handovers" ADD CONSTRAINT "member_handovers_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "impact_transactions" ADD CONSTRAINT "impact_transactions_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "impact_transactions" ADD CONSTRAINT "impact_transactions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_badges" ADD CONSTRAINT "member_badges_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_badges" ADD CONSTRAINT "member_badges_badge_key_badge_definitions_key_fk" FOREIGN KEY ("badge_key") REFERENCES "public"."badge_definitions"("key") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_badges" ADD CONSTRAINT "member_badges_awarded_by_users_id_fk" FOREIGN KEY ("awarded_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_committee_history" ADD CONSTRAINT "member_committee_history_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_committee_history" ADD CONSTRAINT "member_committee_history_committee_id_committees_id_fk" FOREIGN KEY ("committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_committee_history" ADD CONSTRAINT "member_committee_history_academic_term_id_academic_terms_id_fk" FOREIGN KEY ("academic_term_id") REFERENCES "public"."academic_terms"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_committee_history" ADD CONSTRAINT "member_committee_history_placed_by_users_id_fk" FOREIGN KEY ("placed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_profiles" ADD CONSTRAINT "member_profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_role_history" ADD CONSTRAINT "member_role_history_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_role_history" ADD CONSTRAINT "member_role_history_committee_id_committees_id_fk" FOREIGN KEY ("committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_role_history" ADD CONSTRAINT "member_role_history_academic_term_id_academic_terms_id_fk" FOREIGN KEY ("academic_term_id") REFERENCES "public"."academic_terms"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_role_history" ADD CONSTRAINT "member_role_history_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_status_history" ADD CONSTRAINT "member_status_history_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "member_status_history" ADD CONSTRAINT "member_status_history_changed_by_users_id_fk" FOREIGN KEY ("changed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "membership_applications" ADD CONSTRAINT "membership_applications_preferred_committee_id_committees_id_fk" FOREIGN KEY ("preferred_committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "membership_applications" ADD CONSTRAINT "membership_applications_alternate_committee_id_committees_id_fk" FOREIGN KEY ("alternate_committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "membership_applications" ADD CONSTRAINT "membership_applications_academic_term_id_academic_terms_id_fk" FOREIGN KEY ("academic_term_id") REFERENCES "public"."academic_terms"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "membership_applications" ADD CONSTRAINT "membership_applications_assigned_reviewer_id_users_id_fk" FOREIGN KEY ("assigned_reviewer_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "membership_applications" ADD CONSTRAINT "membership_applications_converted_user_id_users_id_fk" FOREIGN KEY ("converted_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "membership_applications" ADD CONSTRAINT "membership_applications_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "mentor_assignments" ADD CONSTRAINT "mentor_assignments_mentor_id_users_id_fk" FOREIGN KEY ("mentor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "mentor_assignments" ADD CONSTRAINT "mentor_assignments_mentee_id_users_id_fk" FOREIGN KEY ("mentee_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "mentor_assignments" ADD CONSTRAINT "mentor_assignments_academic_term_id_academic_terms_id_fk" FOREIGN KEY ("academic_term_id") REFERENCES "public"."academic_terms"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "mentor_assignments" ADD CONSTRAINT "mentor_assignments_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "onboarding_plans" ADD CONSTRAINT "onboarding_plans_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "onboarding_plans" ADD CONSTRAINT "onboarding_plans_academic_term_id_academic_terms_id_fk" FOREIGN KEY ("academic_term_id") REFERENCES "public"."academic_terms"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "onboarding_plans" ADD CONSTRAINT "onboarding_plans_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "onboarding_steps" ADD CONSTRAINT "onboarding_steps_plan_id_onboarding_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."onboarding_plans"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "onboarding_steps" ADD CONSTRAINT "onboarding_steps_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "onboarding_steps" ADD CONSTRAINT "onboarding_steps_completed_by_users_id_fk" FOREIGN KEY ("completed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "people_events" ADD CONSTRAINT "people_events_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "people_events" ADD CONSTRAINT "people_events_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "people_events" ADD CONSTRAINT "people_events_committee_id_committees_id_fk" FOREIGN KEY ("committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "transfer_requests" ADD CONSTRAINT "transfer_requests_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "transfer_requests" ADD CONSTRAINT "transfer_requests_from_committee_id_committees_id_fk" FOREIGN KEY ("from_committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "transfer_requests" ADD CONSTRAINT "transfer_requests_to_committee_id_committees_id_fk" FOREIGN KEY ("to_committee_id") REFERENCES "public"."committees"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "transfer_requests" ADD CONSTRAINT "transfer_requests_requested_by_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "transfer_requests" ADD CONSTRAINT "transfer_requests_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "volunteer_hour_entries" ADD CONSTRAINT "volunteer_hour_entries_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "volunteer_hour_entries" ADD CONSTRAINT "volunteer_hour_entries_submitted_by_users_id_fk" FOREIGN KEY ("submitted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "volunteer_hour_entries" ADD CONSTRAINT "volunteer_hour_entries_approver_id_users_id_fk" FOREIGN KEY ("approver_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "volunteer_hour_entries" ADD CONSTRAINT "volunteer_hour_entries_evidence_id_evidence_id_fk" FOREIGN KEY ("evidence_id") REFERENCES "public"."evidence"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "xp_transactions" ADD CONSTRAINT "xp_transactions_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "xp_transactions" ADD CONSTRAINT "xp_transactions_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "achievements_member_idx" ON "member_achievements" USING btree ("member_id","achieved_at");
--> statement-breakpoint
CREATE INDEX "application_reviews_application_idx" ON "application_reviews" USING btree ("application_id");
--> statement-breakpoint
CREATE INDEX "application_reviews_reviewer_idx" ON "application_reviews" USING btree ("reviewer_id");
--> statement-breakpoint
CREATE INDEX "badge_definitions_active_idx" ON "badge_definitions" USING btree ("active");
--> statement-breakpoint
CREATE INDEX "contribution_rules_active_idx" ON "contribution_rules" USING btree ("active");
--> statement-breakpoint
CREATE INDEX "handovers_user_idx" ON "member_handovers" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX "handovers_status_idx" ON "member_handovers" USING btree ("status");
--> statement-breakpoint
CREATE INDEX "impact_transactions_member_idx" ON "impact_transactions" USING btree ("member_id","created_at");
--> statement-breakpoint
CREATE INDEX "member_badges_member_idx" ON "member_badges" USING btree ("member_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "member_badge_once" ON "member_badges" USING btree ("member_id","badge_key") WHERE "member_badges"."revoked_at" IS NULL;
--> statement-breakpoint
CREATE INDEX "member_committee_history_user_idx" ON "member_committee_history" USING btree ("user_id","start_at");
--> statement-breakpoint
CREATE INDEX "member_committee_history_committee_idx" ON "member_committee_history" USING btree ("committee_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "member_profiles_student_idx" ON "member_profiles" USING btree ("student_id") WHERE "member_profiles"."student_id" IS NOT NULL;
--> statement-breakpoint
CREATE INDEX "member_profiles_status_idx" ON "member_profiles" USING btree ("status");
--> statement-breakpoint
CREATE INDEX "member_role_history_user_idx" ON "member_role_history" USING btree ("user_id","start_at");
--> statement-breakpoint
CREATE UNIQUE INDEX "member_role_history_active" ON "member_role_history" USING btree ("user_id") WHERE "member_role_history"."end_at" IS NULL;
--> statement-breakpoint
CREATE INDEX "member_status_history_user_idx" ON "member_status_history" USING btree ("user_id","created_at");
--> statement-breakpoint
CREATE INDEX "application_status_idx" ON "membership_applications" USING btree ("status");
--> statement-breakpoint
CREATE INDEX "application_reviewer_idx" ON "membership_applications" USING btree ("assigned_reviewer_id");
--> statement-breakpoint
CREATE INDEX "application_term_idx" ON "membership_applications" USING btree ("academic_term_id");
--> statement-breakpoint
CREATE INDEX "mentor_assignments_mentor_idx" ON "mentor_assignments" USING btree ("mentor_id");
--> statement-breakpoint
CREATE INDEX "mentor_assignments_mentee_idx" ON "mentor_assignments" USING btree ("mentee_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "onboarding_plan_term_unique" ON "onboarding_plans" USING btree ("user_id","academic_term_id");
--> statement-breakpoint
CREATE INDEX "onboarding_plans_status_idx" ON "onboarding_plans" USING btree ("status");
--> statement-breakpoint
CREATE UNIQUE INDEX "onboarding_steps_plan_key" ON "onboarding_steps" USING btree ("plan_id","step_key");
--> statement-breakpoint
CREATE INDEX "onboarding_steps_plan_idx" ON "onboarding_steps" USING btree ("plan_id");
--> statement-breakpoint
CREATE INDEX "people_events_entity_idx" ON "people_events" USING btree ("entity_type","entity_id");
--> statement-breakpoint
CREATE INDEX "people_events_member_idx" ON "people_events" USING btree ("member_id");
--> statement-breakpoint
CREATE INDEX "people_events_actor_idx" ON "people_events" USING btree ("actor_id");
--> statement-breakpoint
CREATE INDEX "transfer_requests_user_idx" ON "transfer_requests" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX "transfer_requests_status_idx" ON "transfer_requests" USING btree ("status");
--> statement-breakpoint
CREATE INDEX "volunteer_hours_member_idx" ON "volunteer_hour_entries" USING btree ("member_id","date");
--> statement-breakpoint
CREATE INDEX "volunteer_hours_status_idx" ON "volunteer_hour_entries" USING btree ("status");
--> statement-breakpoint
CREATE INDEX "xp_transactions_member_idx" ON "xp_transactions" USING btree ("member_id","created_at");